### ISSUE TITLE
Add HUD to UIPopoverController instead to a UIWindow

### ISSUE THREAD

**Issue by borut-t** [SVProgressHUD/SVProgressHUD#119]
I am having problems adding HUD to UIPopover. It's actually shown over the whole UIWindow instead of just over the popover.
Am I doing smth wrong or is this just as-is?

**Comment by SixFiveSoftware** [comment]
I ran into a case recently where this was necessary (HUD showed behind a collection view in my view hierarchy) and I wanted to read through these before submitting a PR. I added a very simple method to add to a particular view, only adds one method def to header so it doesn't clutter header, and implementation is small. Would you like me to send the PR?

**Comment by honkmaster** [comment]
Please do so, to allow for a review.

**Comment by runia** [comment]
Please do so, to allow for a code review.
I want add HUD to view but not to window

**Comment by palcalde** [comment]
I've been using MBProgressHud for years and has worked great so far. I just discovered this one and want to give it a try. However, since my app is going to be Universal I wonder if the fact that I can't add it to a subview is going to be a problem in the future. I give a +1 here. 

BTW, I think this issue should be documented properly in the main readme, it's an important thing to now before start using it.

**Comment by ankit-fueled** [comment]
+1 to allow loader to be added on view rather than window only ..

**Comment by tanmays** [comment]
+1 iOS9 has shown multi-window apps would be the norm soon. Having an option to add it to a specific UIView would be the best thing going forward.

**Comment by sebyddd** [comment]
+1 It's kinda annoying to add the HUD at window level when using TabBars. Perhaps the user wants to skip that specific tab, but has to wait till the HUD disappears because user interaction is disabled for the main window.

**Comment by honkmaster** [comment]
If somebody could provide a PR this would be great. I have a larger timeslot for this issue not earlier than end next month due to some private things and many customer projects.

**Comment by SixFiveSoftware** [comment]
I believe this seems kind of akin to the PR I submitted a while back: https://github.com/TransitApp/SVProgressHUD/pull/394.

**Comment by honkmaster** [comment]
Sorry I missed it. The PR is basically functionally, but incomplete. <=> This was I think also the reason, why I did not merge it. Let me explain what I mean with incomplete: You added the 'fromView:(UIView *)aView' modified methods only for 'showWithStatus' and 'showErrorWithStatus'. To be "complete" this needs also to be added to the other methods like 'showSuccessWithStatus' and 'showImage'.

**Comment by honkmaster** [comment]
Could you please update your PR #394 for merge?

**Comment by SixFiveSoftware** [comment]
Hey @honkmaster sorry for the delay in getting back to you, got OBE with work, book, etc. I'm updating many of the methods to accommodate being shown from a particular view and I'm seeing what you mean about it adding complexity due to each type of show method needing several more method signatures just to add the custom view parameter from which to be shown. 

Here's a question: are you considering Swift at all for this? It would really shorten methods up and the list of possible signatures by using default parameters. If not, I may need to take some time to think about if this could be implemented differently without adding tens of other method signatures, making the searchable list into a "WTF" moment for anyone using this. I really want to help, but at the same time, I don't want to add unreasonable complexity for everyone.

**Comment by honkmaster** [comment]
Swift is not at my agenda at the moment.

**Comment by SixFiveSoftware** [comment]
Ok, let me take a step back from this and review the purpose of what I was adding, to see if it can be done differently without adding a ton of complexity.

**Comment by honkmaster** [comment]
👍🏻

**Comment by honkmaster** [comment]
Any update?

**Comment by honkmaster** [comment]
...

**Comment by SixFiveSoftware** [comment]
I haven't done anything with the PR, so if you're waiting on me to close, go for it, and please accept my apologies for not replying sooner. I don't know if closing will solve the initial reason for this discussion, though.

**Comment by honkmaster** [comment]
I do not want to stop the "discussion". But the PR is open since 2012, nobody has given input code-wise and as sam mentioned before this requires a lot of refactor and will make the code complex.

**Comment by SixFiveSoftware** [comment]
Perhaps I misunderstood your comment "final call". Final call for what, closing the PR? Or just an update? I can't speak for everyone on this discussion, but if waiting for me to say "close it", I'd say close it. I haven't done anything with it, and don't have the resources now to devote to it. I'm using my fork that has the few methods added I need and I'm happy with it.

**Comment by allfou** [comment]
Here is my quick fix to allow custom UIView container:

1- Similar to all the custom properties in  SVProgressHUD.h (e.g. minimumSize, ringThickness) add a custom property 

**@property (assign, nonatomic) UIView *containerView;** 

2- Add a public setter for this new property similar to:

+ (void)setMinimumSize:(CGSize)minimumSize; 
+ (void)setRingThickness:(CGFloat)ringThickness; 
etc..
**+ (void)setContainerView:(UIView*)containerView;**

3- in SVProgressHUD 

3-1. Add a private setter similar to:

- (void)setMinimumSize:(CGSize)minimumSize {
    if (!_isInitializing) _minimumSize = minimumSize;
}

- (void)setRingThickness:(CGFloat)ringThickness {
    if (!_isInitializing) _ringThickness = ringThickness;
}

etc.

**- (void)setContainerView:(UIView *)containerView {
    if (!_isInitializing) _containerView = containerView;
}**

3-2. Add the following method below -(void)updateViewHierarchy{}

**- (void)updateViewHierarchyForContainerView {
    [_containerView addSubview:self.overlayView];
    
    // Add self to the overlay view
    if(!self.superview){
        [self.overlayView addSubview:self];
    }
    if(!self.hudView.superview) {
        [self addSubview:self.hudView];
    }
}**

3-3. Call **updateViewHierarchyForContainerView** this new method in showProgress instead of **updateViewHierarchy**

**- (void)showProgress:(float)progress status:(NSString*)status {
    __weak SVProgressHUD *weakSelf = self;
    [[NSOperationQueue mainQueue] addOperationWithBlock:^{
        __strong SVProgressHUD *strongSelf = weakSelf;
        if(strongSelf){
            // Update / Check view hierarchy to ensure the HUD is visible
            [strongSelf updateViewHierarchyForContainerView];  // New Method!
            //[strongSelf updateViewHierarchy];
    ....**

4- Then finally, in your own class - set the UIView Container prior to showing the SVProgressHUD similar to all the other customization available.

        [SVProgressHUD setContainerView:YOUR_OWN_UIVIEW];
        [SVProgressHUD show];

5- Optional: you may want to re-adjust the position of the spinner based on your own UI layout...

Good luck!

**Comment by honkmaster** [comment]
This can now be solved in an upcoming release using `setContainerView:`
