### ISSUE TITLE
Using SVProgressHUD

### ISSUE THREAD

**Issue by googoodalls** [SVProgressHUD/SVProgressHUD#390]

**Comment by MuscleRumble** [comment]
I've already opened a new issue #432 but I just wanted to let you know that I've also read this issue. I can't get it working even in my minimal "test" project (in issue #432). What am I doing fundamentally wrong? Where do I have to define that macro?

**Comment by wolikeq** [comment]
hello，when I used it in my project,  there had some problem,like this:
 [SVProgressHUD showSuccessWithStatus:@"cool!!!"];

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(0x183e0cf48 0x1992b7f80 0x183e0ce90 0x184cd9bf8 0x184cd9b7c 0x10010126c 0x1000ff690 0x100709c68 0x10070aae0 0x1000ff59c 0x100100674 0x100117194 0x1893d7cfc 0x1893d7c78 0x1893bf930 0x1893d7590 0x1893d71c0 0x1893cfcdc 0x1893a04a4 0x18939e76c 0x183dc4544 0x183dc3fd8 0x183dc1cd8 0x183cf0ca0 0x18f274088 0x189408ffc 0x1000ee198 0x199afa8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

and  could you help me?

**Comment by honkmaster** [comment]
Have you checked that SVProgressHUD.bundle is added to Targets->Build Phases->Copy Bundle Resources

**Comment by wolikeq** [comment]
yeah,but to little avail..........

**Comment by honkmaster** [comment]
???

**Comment by NSObject-RC** [comment]
？
