### ISSUE TITLE
UIBlurEffect can't work 

### ISSUE THREAD

**Issue by zymxxx** [SVProgressHUD/SVProgressHUD#517]
![1](https://cloud.githubusercontent.com/assets/6263633/11271538/77408e60-8f01-11e5-8c67-1876e93ae8f6.png)
![2](https://cloud.githubusercontent.com/assets/6263633/11271539/7751da8a-8f01-11e5-8d59-46623288c61e.png)

Remove background color,but the effect also would not work.
is it Bug?

And here:

![3](https://cloud.githubusercontent.com/assets/6263633/11271550/9367ee76-8f01-11e5-9aa9-30e76ee891bb.png)
![4](https://cloud.githubusercontent.com/assets/6263633/11271549/936529ac-8f01-11e5-8dfe-7ce854dc78e6.png)
![5](https://cloud.githubusercontent.com/assets/6263633/11271551/9370e68e-8f01-11e5-9ba1-4a5b13db8f21.png)

**Comment by zymxxx** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by maplelover** [comment]
I also encountered this problem.

**Comment by lgauthier** [comment]
Another related issue here is that the `hudView`'s background color is being reset to white or black every time it is accessed when one of the blur styles is used.

```
- (UIView*)hudView {
    if(!_hudView) {
        _hudView = [[UIView alloc] initWithFrame:CGRectZero];
        _hudView.layer.masksToBounds = YES;
        _hudView.autoresizingMask = UIViewAutoresizingFlexibleBottomMargin | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleLeftMargin;
    }
    
    // Update styling
    _hudView.layer.cornerRadius = self.cornerRadius;
    _hudView.backgroundColor = self.backgroundColorForStyle;
    
    return _hudView;
}
```

The problem is that `backgroundColorForStyle` returns white and black for the styles that have the blur:

```
- (UIColor*)backgroundColorForStyle {
    if(self.defaultStyle == SVProgressHUDStyleLight) {
        return [UIColor whiteColor];
    } else if(self.defaultStyle == SVProgressHUDStyleDark) {
        return [UIColor blackColor];
    } else {
        return self.backgroundColor;
    }
}
```

I believe the solution here is to return `[UIColor clearColor]` when using the light and dark styles on iOS 8+. I might be able to find some time later today to send a PR.
