### ISSUE TITLE
Deprecated showSuccessWithStatus:maskType:

### ISSUE THREAD

**Issue by wiistriker** [SVProgressHUD/SVProgressHUD#519]
It looks like a good approach to have clean api like [SVProgressHUD showSuccessWithStatus:@"Status"]; with default mask type, but when we have app which use not only one mask type our code becomes really ugly:

before:
```
[SVProgressHUD showSuccessWithStatus:@"Status" maskType:SVProgressHUDMaskTypeNone];
```

after:
```
SVProgressHUDMaskType lastMaskType = ???;
[SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeNone];
[SVProgressHUD showSuccessWithStatus:@"Status"];
[SVProgressHUD setDefaultMaskType:lastMaskType];
```

And it seems there is no API to retrieve default mask type.

I think it will be much better to remove deprecations for all methods with maskType argument?

**Comment by honkmaster** [comment]
To be honest. Why would you use different types of masks? This is very un-iOS-esque. Can you give me a valid use case?

**Comment by wiistriker** [comment]
I use showSuccessWithStatus as simple notification about some action. And if i use it with black mask type UI was blocked for a while.

Maybe i should use another type of notifications ofcourse

**Comment by honkmaster** [comment]
From my and the usability point of view I would always use the same mask. This corresponds to the way apple is doing this (with UIAlertView, UIActionSheet or UIAlertController). However, maybe there are some other contributions that might help in this discussion.

**Comment by cmckni3** [comment]
I agree with deprecating `showSuccessWithStatus:maskType:` and shifting more towards the `UIAppearance` approach. Changing the mask type because the UI was blocked doesn't make much design sense to me. I think an indeterminate loading animation and some text communicates that better than changing the color.

**Comment by ldiqual** [comment]
@honkmaster I'd like to bring up what I believe is a valid usecase here. We use `mask = .Clear` when something is processing (saving a form for instance) and `mask = .None` when showing an error or a success. The reasoning is that we want users to be able to interact with the screen as soon as they get feedback from the app (eg: tap "submit" again after an error), but don't want them to tap anywhere when we're doing network calls that have to block user interactions. There's nothing more annoying than having to wait 1-2s after an error to tap on "retry".

You seem to indicate in https://github.com/SVProgressHUD/SVProgressHUD/issues/581 that there are better options available. What would you use or do differently in the following cases?


![simulator screen shot mar 24 2016 4 03 50 pm](https://cloud.githubusercontent.com/assets/941453/14033794/77bbc8be-f1da-11e5-92f2-e1619db7880c.png)
![simulator screen shot mar 24 2016 4 06 51 pm](https://cloud.githubusercontent.com/assets/941453/14033793/77b9f8d6-f1da-11e5-9671-292cc6054bfe.png)

**Comment by honkmaster** [comment]
Regarding your first use case: Why not save in the background? From the users point of view I would expect that a save operation is instant (especially on iOS). In addition I would never show success for save operation. Again, as a user I would expect the save is always successful. In the case of an error I would not use the `HUD` at all. Here, I would display an `UIAlertController` telling the user what happened with a button to try again:

Title: "Save error"
Message: "An error happened during save of your file. This is due to FOO. Do you want to try again?"
Buttons: "Cancel", "Try again"

What do you think?

P.S.: To be honest I hate the `clear` maskType as it blocks user interaction, and the user does not know why. However, it is still in the component for legacy reasons. Apple for example always uses an coloured overlay (black) or a gradient to show a blocked UI.

**Comment by AcidicSkittles** [comment]
I personally would still like to have the ```showSuccessWithStatus:maskType:```. For example, if I'm saving an image, there's a couple seconds where it's downloading so it's showing the progress of that task. When it finishes, I think it's nice having the ```SVProgressHUDMaskTypeNone``` when showing a success message as soon as it saves. Then I can hit the back button on my navigation controller before the success message is dismissed. 

Just my 2 cents.
