### ISSUE TITLE
SVProgressHUD is showing behind UIView

### ISSUE THREAD

**Issue by HannesVDB** [SVProgressHUD/SVProgressHUD#528]
I'm trying to show a progressHUD on my viewdidload but it appears behind my UIView?

You can see the progressHUD in the middle of the image..

<img width="279" alt="screen shot 2015-12-16 at 22 02 51" src="https://cloud.githubusercontent.com/assets/9309294/11853871/c3101352-a440-11e5-9d70-c26e0a9db4fd.png">

**Comment by honkmaster** [comment]
Could you provide a sample project where the bug appears?

**Comment by tedz** [comment]
![c7ef29ea-6ce9-4e74-b383-d94ac5183c38](https://cloud.githubusercontent.com/assets/1435774/12443807/b4af85ca-bf95-11e5-837c-4222b9be91d7.png)

```-(void)showStatus:(NSString *)status { ... }```

This line of code ```strongSelf.hudView.alpha = 1;```should be included in `else{ ... }`, otherwise, message hud view won't show for second time, when I set defaultMaskType to `SVProgressHUDMaskTypeGradient`;

**Comment by honkmaster** [comment]
The code is not like this anymore, is the issue therefore still alive?

**Comment by HannesVDB** [comment]
Hi,

This issue is not relevant anymore. 

Kind regards

**Comment by honkmaster** [comment]
Thanks for the fast feedback.
