### ISSUE TITLE
Carthage building error on SVProgressHUD "2.0.1"

### ISSUE THREAD

**Issue by denny1314** [SVProgressHUD/SVProgressHUD#585]
when I run "carthage update --platform iOS"
I got this error messages
______
The following build commands failed:
	Ld /Users/fortinet/Library/Developer/Xcode/DerivedData/SVProgressHUD-gvktundsqvzqwobklivjdudvqtgq/Build/Intermediates/SVProgressHUD.build/Release-iphoneos/SVProgressHUD-Framework.build/Objects-normal/armv7/SVProgressHUD normal armv7
(1 failure)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	Ld /Users/fortinet/Library/Developer/Xcode/DerivedData/SVProgressHUD-gvktundsqvzqwobklivjdudvqtgq/Build/Intermediates/SVProgressHUD.build/Release-iphoneos/SVProgressHUD-Framework.build/Objects-normal/armv7/SVProgressHUD normal armv7
(1 failure)
_______

Note: svprogresshud "2.0" doesn't have this issue

**Comment by leo-marchand-hs** [comment]
I'm seeing the same thing as well.

**Comment by honkmaster** [comment]
Hey guys: Some honest words first. I added Carthage / accepted a PR to add carthage because it seemed like a good idea to have an alternative to Cocoapods. In addition the overheads were small. 

However, recently Carthage throws often errors like the one above. I do not use Carthage myself and can therefore not provide support. The community is not helping either, they just cry out loud without the genuine will to investigate on their on. This is not the case with the Cocoapods people.

Overall, I therefore will remove Carthage with one of the next releases (probably 2.1) unless good reason exists and someone from the community handles the technical support (longtime).

**Comment by hefgi** [comment]
same here

**Comment by justin** [comment]
I'll take over as point Carthage support if you agree to keep maintain support for it. I'm looking into what's broken now. PR when i figure it out
