### ISSUE TITLE
HUD is not show immediately after dismiss.

### ISSUE THREAD

**Issue by r-plus** [SVProgressHUD/SVProgressHUD#611]
HUD is not showing in below use case. (version 2.0.3)

```
        dispatch_async(dispatch_get_main_queue(), { () -> Void in
            SVProgressHUD.show()
            SVProgressHUD.dismiss()
            SVProgressHUD.show()
        })
```

**Comment by caojunhua** [comment]
Swift?

**Comment by ileitch** [comment]
I'm seeing this also, just tried and it affects 2.0 also.

**Comment by ileitch** [comment]
In my case I'm calling from Obj-C

**Comment by juanuribeo13** [comment]
I'm also having this problem, I had to go back to version 1.1.3 in which it works fine.

**Comment by chika-kasymov** [comment]
I also have this issue :(

**Comment by mbalex** [comment]
There is a race condition using animations and dismiss.

Just deactivate animations using
+ (void)setFadeInAnimationDuration:(NSTimeInterval)duration;        // default is 0.15 seconds
+ (void)setFadeOutAnimationDuration:(NSTimeInterval)duration;       // default is 0.15 seconds

The completionBlock of the **fade out** animation will remove all views from the window view, 0.15s after the dismiss is called, regardless if those views are currently using in a **fade in** animation.
That call removing all views should make sure nothing is actually using or will be using the views.

Since those animations are not race condition free, I would suggest disabling them altogether (not only fade out).

**Comment by honkmaster** [comment]
Working on a fix. However, PR are always welcome.

**Comment by honkmaster** [comment]
Should be fixed with the latest commit, please check the current master and provide feedback.

**Comment by honkmaster** [comment]
You are welcome, I am very sorry that I was not able to fix it earlier.
