### ISSUE TITLE
Using SVProgressHUD in both extension and app

### ISSUE THREAD

**Issue by happiehappie** [SVProgressHUD/SVProgressHUD#643]
Guys, 

Sorry just need some clarification, after adding SV_APP_EXTENSIONS=1 to my pod's SVProgressHUD, does this make my app not being able to use SVProgressHUD?
Cause for some reason .show() doesn't do anything now.

**Comment by happiehappie** [comment]
[TestSV.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/354379/TestSV.zip)

**Comment by happiehappie** [comment]
[TestSV.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/354401/TestSV.zip)

**Comment by fylock** [comment]
Same behavior here. Setting the extensionView does not seam to do anything either.

**Comment by happiehappie** [comment]
This is old. Does anyone know if this is an intended behaviour or? I reckon
it's not a rare use case that I want to use SV for both my app and extension

**Comment by svintus** [comment]
I just ran into this issues myself. Unfortunately, it is a serious limitation of CocoaPods, rather than an SVProgressHUD bug. Ideally, you should be able to bundle 2 versions of the framework - one with SV_APP_EXTENSIONS=1 to use in the extension, and one without. CocoaPods doesn't currently allow that :(

Another solution to this would be figuring out how to make SVProgressHUD always work without depending on API's not available in the extensions. I just had a brief look at the source and, while not impossible, it will require significant changes.
