### ISSUE TITLE
waiting time

### ISSUE THREAD

**Issue by xiaoxudage** [SVProgressHUD/SVProgressHUD#661]
The latest version of the waiting time is too long

**Comment by honkmaster** [comment]
Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Why is the issue relevant, why do you want to change something etc. Programmers make a lot of efforts on writing open source components. Thus, do the community a favor,  show respect by writing a better issue.

**Comment by benpackard** [comment]
I agree that this description isn't very helpful but let's be careful not to discourage people from reporting issues, especially those who might be new to open source and don't know the ropes. Rather than haranguing the reporter, are there project guidelines for new issues that can be linked to? An example of a good issue description?

**Comment by wooster** [comment]
@honkmaster This is probably referring to the changes made in: 971210c7fceb0f62d7ae16fea92e7b91e99705ff

Which, effectively, changed the default dismiss time interval to 5 seconds in most cases. The previous behavior seemed more correct, albeit misleadingly named, given timing of other UI on the system.

**Comment by sweetyMo** [comment]
[SVProgressHUD setMinimumDismissTimeInterval:0.5];
Set the minimum time，default is 5.0 seconds

**Comment by honkmaster** [comment]
@sweetyMo is correct.
