### ISSUE TITLE
2.0.4 style regression

### ISSUE THREAD

**Issue by ileitch** [SVProgressHUD/SVProgressHUD#686]
Appearance using 2.0.3:
![screen shot 2016-11-17 at 3 31 36 pm](https://cloud.githubusercontent.com/assets/48235/20376552/c358dd0e-acdb-11e6-9741-1cd5cc892e8c.png)

with 2.0.4:
![screen shot 2016-11-17 at 3 35 49 pm](https://cloud.githubusercontent.com/assets/48235/20376563/cf7e7422-acdb-11e6-930f-348598c3fb9b.png)

The only configuration we're using is:
```
[SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeBlack];
```

**Comment by iBicha** [comment]
I'm experiencing this as well. Actually, even with 2.0.3, setting the foreground color doesn't work.
reverting to 1.1.3 solved the problem.

**Comment by honkmaster** [comment]
This is actually intended. Since 2.0 the HUD has a basic color (white) and blurs a little with the background (here your red background). There was a bug in 2.0.1 - 2.0.3 so live blurring was malfunctioning. This is now fixed. One could argue that the blur is to strong, and that there is to much red in this case. To achieve the old behaviour (only white) use `SVProgressHUDStyleCustom` with setting background and foreground.

**Comment by honkmaster** [comment]
When looking at your sample maybe we have to fiddle around with `UIBlurEffectStyle` in `updateBlurBounds`.

**Comment by ileitch** [comment]
Yeah I'd say it's a little too strong, but we want the old style anyway so `SVProgressHUDStyleCustom` works for me 👍

**Comment by honkmaster** [comment]
Could you try `UIBlurEffectStyleExtraLight` instead of `UIBlurEffectStyleLight` in line 532 of `SVProgressHUD.m` and report back?

**Comment by iBicha** [comment]
i suggest that calling `setForegroundColor` or `setBackgroundColor` would automatically change style to `custom`.

**Comment by honkmaster** [comment]
Pull request is welcome.

**Comment by iBicha** [comment]
PR #692
