### ISSUE TITLE
Bridging header not working, I have to import it in every swift file

### ISSUE THREAD

**Issue by JLowner** [SVProgressHUD/SVProgressHUD#775]
Hi, I'm new with swift.
I installed SVProgressHUD by cocoapods, with use_framework
This is my bridging header
`#ifndef Header_h //bridge`
`#define Header_h`

`#import <Google/SignIn.h>`
`#import <SVProgressHUD/SVProgressHUD.h>`
`#import <SDWebImage/UIImageView+WebCache.h>`

`#endif /* Header_h */`

This is my code in a viewController.swift file

`        SVProgressHUD.show()`
`        UIImageView.init().sd_setImage(with: URL.init(string: "111"))`

sadly it gave me unresolved identifier 'SVProgressHUD' error, while SDWebImage is working fine.

I could solve this by adding
`import SVProgressHUD`
in the beginning of my swift file, that means I'll have to import it over and over for every swift file. Also when i import this it is having a red strikethrough for SVProgressHUD.

Is anyone having the same problem?

**Comment by JLowner** [comment]
The swift version is 3

**Comment by JLowner** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'SkillTagzApp' do
    pod 'Alamofire', '~> 4.4'
    pod 'MQTTClient'
	pod 'SDWebImage', '~>3.8'
	pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
	pod 'GoogleMaps'
	pod 'GooglePlaces'
	pod 'GooglePlacePicker'
	pod 'RSKImageCropper'
	pod 'MJRefresh'
    pod 'Google/SignIn'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
end

This is what I installed

**Comment by aylwing** [comment]
I believe this is a normal occurrence. However, there is a way around it. Since SVProgressHUD lives in the view layer of your application you can create an extension for UIViewController in a separate swift file and import SVProgressHUD into that file. Then you can create a function for example: func showErrorWith(title: String) and have SVProgressHUD take that parameter from within that function's body. That way you can call those functions on any viewController, and not have to worry about importing SVProgressHUD into every UIViewController or subclass of UIViewController.
