### ISSUE TITLE
v2.1.2 in iOS8.3 no display message with several times

### ISSUE THREAD

**Issue by jhchenchong** [SVProgressHUD/SVProgressHUD#787]

**Comment by zvving** [comment]
+1

**Comment by honkmaster** [comment]
This issue is not described properly. Thus we can not help at the moment. Maybe it is already solved?

FYI: Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect for the programmers that make a lot of efforts on writing open source components.
