### ISSUE TITLE
Removed important feature (popActivity)

### ISSUE THREAD

**Issue by zsjenei** [SVProgressHUD/SVProgressHUD#823]
Description is under this commit: https://github.com/SVProgressHUD/SVProgressHUD/commit/44ab58995f2b90f73fac966b61fff792a45ad0ec
The commit is about visual upgrade although in same time it is removing a key feature and a working public function. I am asking for rollback of the removed functionality. Additionally in future would be nice to not make functional changes in a commit dedicated to only visuals.

**Comment by pgawlowski** [comment]
#824

**Comment by honkmaster** [comment]
I have very (very) limited time.  A simple revert can be done. However, I keep my opinion. `popActivity` does not work as expected. If an activity is _popped_, a previous message should be displayed.

1. Show with message "1"
2. Show with message "2"
3. `popActivity`
4. Message "1" should be visible.

This is what I understand by stacking HUDs and using a pop method. See also: https://en.wikipedia.org/wiki/Stack_(abstract_data_type)

**Comment by pgawlowski** [comment]
Most of time popActivity is being used to one-type activity.

Another thing - I don't agree at all to be honest. Most of situations we're stacking activities during multiple async requests.

So
Start request with message 1.
Start request with message2
popActivity()

We are unable to determine which activity is done right now and because all of these activities were triggered in asnyc way, from the user perspective it is enough to be aware about last activity triggered (message 2) cause the whole asyc flow is in progress and the main concert is to indicate the whole process. Swap of message can be a little bit confusing for end point user.

What's more I believe that stacking in most cases appear for simple indicators (without messages or with same message)  because of the issue I pointed - in most cases you don't need info which activity is done, you just need to be aware that whole bunch of asyc requests are in progress. 

It is hard to find the proper solution. I'm using SVProgress in every application and I never had a need to pop to previous message.

Let's imagine async loading of products and users.

1. Trigger product load
2. Show "Loading products..."
3. Trigger users load
4. Show "Loading users.."
Loading users is done first
5. Pop to loading products.
User confusion - "What the hell? We've been loading products earlier :)"

What do you think about merging this solution and later on let's introduce another method like popActivityNatural or sth that will pop to previous indicator? In that case we need not only a counter but a real stack of activities.

**Comment by honkmaster** [comment]
I reverted to include popActivity. However, we still should search for a real stack-like solutions
