### ISSUE TITLE
SVProgressHUD  setSuccessImage  显示出来是一块黑色的

### ISSUE THREAD

**Issue by miss-mao** [SVProgressHUD/SVProgressHUD#825]
[SVProgressHUD]  setSuccessImage 显示出来是一块黑色的，并不是我设置的图

**Comment by honkmaster** [comment]
The repository language is english. Please reopen with an english description if necessary, otherwise the issue remains closed for now.

FYI: Questions like this, are the reason people burn out on open source. Don't let others do your work, give good questions (in a language everybody understands, especially the maintainer), follow issue guidelines, provide a demo project or tell what you have already done to solve the problem.
