### ISSUE TITLE
thread 1 breakpoint 1.3

### ISSUE THREAD

**Issue by youlianchun** [SVProgressHUD/SVProgressHUD#838]
当代码执行到   _statusLabel = [[UILabel alloc] initWithFrame:CGRectZero]; 编译器会断点停止，提示thread 1 breakpoint 1.3

When I'm debugging, the compiler will prompt “thread 1 breakpoint 1.3” in “_statusLabel = [[UILabel alloc] initWithFrame:CGRectZero];”，at row 1291 in "SVProgressHUD.m" file

**Comment by vincentsong** [comment]
I got save issue recently

**Comment by aemgtz** [comment]
I faced the same result. 
Any update ?

**Comment by honkmaster** [comment]
This issue is not described properly, e.g. the title is very poor. Thus we can not help at the moment.

FYI: Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect for the programmers that make a lot of efforts on writing open source components.

**Comment by fukemy** [comment]
@honkmaster that is kind of bug, not anything other
