### ISSUE TITLE
SVProgressHUD showProgress:status:]_block_invoke  has a crash

### ISSUE THREAD

**Issue by Aoce** [SVProgressHUD/SVProgressHUD#840]
0Crashed: com.apple.main-threadSIGABRT ABORT 0x0000000186ca9348 Raw Text
--
0 | libsystem_kernel.dylib | __pthread_kill + 8
11 | UIKit | +[UIWindow allWindowsIncludingInternalWindows:onlyVisibleWindows:forScreen:] + 188
12 | XXXX | SVProgressHUD.m line 1367-[SVProgressHUD frontWindow]
13 | XXXX | SVProgressHUD.m line 539-[SVProgressHUD updateViewHierarchy]
14 | XXXX | SVProgressHUD.m line 772__37-[SVProgressHUD showProgress:status:]_block_invoke
15 | Foundation | __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
30 | UIKit | UIApplicationMain + 208
31 | XXXX | main.m line 16main
32 | libdyld.dylib | start + 4

**Comment by honkmaster** [comment]
This issue is not described properly. Thus we can not help at the moment.

FYI: Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect for the programmers that make a lot of efforts on writing open source components.
