### ISSUE TITLE
Exercised class for selector implementation needs to be pushed

### ISSUE THREAD

**Issue by ecgbao** [SVProgressHUD/SVProgressHUD#869]
-[SVProgressHUD hudView] (in SnapECG) (SVProgressHUD.m:1268)

**Comment by honkmaster** [comment]
This issue is not described properly. Thus we can not help at the moment.

FYI: Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect for the programmers that make a lot of efforts on writing open source components.
